<?php
/**
 * PlantBasicResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SunDataMetropolisClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SunData API
 *
 * SunData API OpenAPI Specification.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: admin@sundata.nl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SunDataMetropolisClient;

use PHPUnit\Framework\TestCase;

/**
 * PlantBasicResponseTest Class Doc Comment
 *
 * @category    Class
 * @description PlantBasicResponse
 * @package     SunDataMetropolisClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PlantBasicResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PlantBasicResponse"
     */
    public function testPlantBasicResponse()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "owning_company_id"
     */
    public function testPropertyOwningCompanyId()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "tag_ids"
     */
    public function testPropertyTagIds()
    {
    }

    /**
     * Test attribute "company_ids"
     */
    public function testPropertyCompanyIds()
    {
    }
}
