<?php
/**
 * SatelliteApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  SunDataMetropolisClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SunData API
 *
 * SunData API OpenAPI Specification.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: admin@sundata.nl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SunDataMetropolisClient\Test\Api;

use \SunDataMetropolisClient\Configuration;
use \SunDataMetropolisClient\ApiException;
use \SunDataMetropolisClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SatelliteApiTest Class Doc Comment
 *
 * @category Class
 * @package  SunDataMetropolisClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SatelliteApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getPlantDetails
     *
     * Get plant details.
     *
     */
    public function testGetPlantDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPlantMeterDetails
     *
     * Get the meter and plant details.
     *
     */
    public function testGetPlantMeterDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
