name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: geoadmin/github-tag-action@feat-BGDIINF_SB-2357-fix-semver-with-v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Release new package on private Satis/Composer
        run: wget https://packages.sddns.nl/admin/satis/buildRun

